Build only with python 3.9
python 3.5 is outdated, so it's dropped.

python 3.10 returns an traceback like:

```
Run make publish
virtualenv/bin/pelican /home/runner/work/ubucon.de/ubucon.de/content -o /home/runner/work/ubucon.de/ubucon.de/output -s /home/runner/work/ubucon.de/ubucon.de/publishconf.py
Traceback (most recent call last):
  File "/home/runner/work/ubucon.de/ubucon.de/virtualenv/bin/pelican", line 5, in <module>
    from pelican import main
  File "/home/runner/work/ubucon.de/ubucon.de/virtualenv/lib/python3.10/site-packages/pelican/__init__.py", line 17, in <module>
    from pelican.log import init  # noqa
  File "/home/runner/work/ubucon.de/ubucon.de/virtualenv/lib/python3.10/site-packages/pelican/log.py", line 8, in <module>
    from collections import Mapping, defaultdict
ImportError: cannot import name 'Mapping' from 'collections' (/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/collections/__init__.py)
make: *** [Makefile:58: publish] Error 1
```